# Generated by Django 4.2.4 on 2023-09-20 14:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("localizacao", models.CharField(max_length=250)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj", models.CharField(max_length=250)),
                ("nome_empresa", models.CharField(max_length=250)),
                ("categoria_empresa", models.CharField(max_length=250)),
                ("quitado", models.BooleanField(default=False)),
                (
                    "data_reserva",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "stand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finecap.stand"
                    ),
                ),
            ],
        ),
    ]
