# Generated by Django 4.2.4 on 2023-08-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finecap", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="quitato",
            field=models.BooleanField(default=False),
        ),
    ]
